name: bit-academy-php

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bit-php
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "127.0.0.1:80:80"
    networks:
      - backend
  mysql:
    image: mysql:8.4
    container_name: bit-mysql
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin:5.2-apache
    container_name: bit-phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - backend
networks:
  backend:
volumes:
  data:
